//general
export const SET_PROCCESSING = 'SET_PROCCESSING'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
//user
export const SET_USER = 'SET_USER'
export const UNSET_USER = 'UNSET_USER'
//userDATA
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA'
export const SET_PROFILE_IMG = 'SET_PROFILE_IMG'
export const SET_NOTIFICATION_MSGS = 'SET_NOTIFICATION_MSGS'
export const SET_BASE_SETTINGS = 'SET_BASE_SETTINGS'